## Kfold Cross Validation for Clasification

In [ ]:
import pandas as pd
from sklearn import model_selection

In [15]:
df = pd.read_csv('./resources/wine_quality/winequality-red.csv')
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [16]:
df['kfold'] = -1
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,kfold
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,-1
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,-1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,-1
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,-1
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,-1

In [17]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,kfold
0,7.4,0.68,0.16,1.8,0.078,12.0,39.0,0.99770,3.50,0.70,9.9,6,-1
1,10.6,0.48,0.64,2.2,0.111,6.0,20.0,0.99700,3.26,0.66,11.7,6,-1
2,6.7,1.04,0.08,2.3,0.067,19.0,32.0,0.99648,3.52,0.57,11.0,4,-1
3,11.6,0.41,0.58,2.8,0.096,25.0,101.0,1.00024,3.13,0.53,10.0,5,-1
4,7.2,0.62,0.06,2.5,0.078,17.0,84.0,0.99746,3.51,0.53,9.7,5,-1

In [20]:
kf = model_selection.KFold(n_splits=5)

In [21]:
type(kf)

sklearn.model_selection._split.KFold

In [30]:
for fold, (trn_, val_) in enumerate(kf.split(X=df)):
    df.loc[val_, 'kfold'] = fold

In [33]:
df = df.sample(frac=1).reset_index(drop=True)
df.head(40)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,kfold
0,10.3,0.430,0.44,2.4,0.214,5.0,12.0,0.99940,3.19,0.63,9.5,6,3
1,8.9,0.745,0.18,2.5,0.077,15.0,48.0,0.99739,3.20,0.47,9.7,6,3
2,10.0,0.560,0.24,2.2,0.079,19.0,58.0,0.99910,3.18,0.56,10.1,6,0
3,6.8,0.680,0.21,2.1,0.070,9.0,23.0,0.99546,3.38,0.60,10.3,5,3
4,7.0,0.540,0.09,2.0,0.081,10.0,16.0,0.99479,3.43,0.59,11.5,6,2
5,6.4,0.570,0.14,3.9,0.070,27.0,73.0,0.99669,3.32,0.48,9.2,5,4
6,12.7,0.600,0.49,2.8,0.075,5.0,19.0,0.99940,3.14,0.57,11.4,5,4
7,8.4,0.340,0.42,2.1,0.072,23.0,36.0,0.99392,3.11,0.78,12.4,6,4
8,9.8,0.880,0.25,2.5,0.104,35.0,155.0,1.00100,3.41,0.67,11.2,5,0
9,10.1,0.270,0.54,2.3,0.065,7.0,26.0,0.99531,3.17,0.53,12.5,6,0
10,6.1,0.400,0.16,1.8,0.069,11.0,25.0,0.99550,3.42,0.74,10.1,7,2
11,6.3,0.390,0.16,1.4,0.080,11.0,23.0,0.99550,3.34,0.56,9.3,5,2
12,10.4,0.440,0.42,1.5,0.145,34.0,48.0,0.99832,3.38,0.86,9.9,3,2
13,8.2,0.340,0.37,1.9,0.057,43.0,74.0,0.99408,3.23,0.81,12.0,6,4
14,10.7,0.350,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.0,8,4
15,10.5,0.360,0.47,2.2,0.074,9.0,23.0,0.99638,3.23,0.76,12.0,6,0
16,10.2,0.670,0.39,1.9,0.054,6.0,17.0,0.99760,3.17,0.47,10.0,5,0
17,7.7,0.620,0.04,3.8,0.084,25.0,45.0,0.99780,3.34,0.53,9.5,5,0
18,8.0,0.180,0.37,0.9,0.049,36.0,109.0,0.99007,2.89,0.44,12.7,6,0
19,9.3,0.610,0.26,3.4,0.090,25.0,87.0,0.99975,3.24,0.62,9.7,5,3
20,8.2,0.380,0.32,2.5,0.080,24.0,71.0,0.99624,3.27,0.85,11.0,6,1
21,12.0,0.280,0.49,1.9,0.074,10.0,21.0,0.99760,2.98,0.66,9.9,7,2
22,7.2,0.410,0.30,2.1,0.083,35.0,72.0,0.99700,3.44,0.52,9.4,5,3
23,12.0,0.390,0.66,3.0,0.093,12.0,30.0,0.99960,3.18,0.63,10.8,7,0
24,6.7,0.540,0.13,2.0,0.076,15.0,36.0,0.99730,3.61,0.64,9.8,5,4
25,8.3,0.715,0.15,1.8,0.089,10.0,52.0,0.99680,3.23,0.77,9.5,5,2
26,7.0,0.590,0.00,1.7,0.052,3.0,8.0,0.99600,3.41,0.47,10.3,5,3
27,9.8,0.340,0.39,1.4,0.066,3.0,7.0,0.99470,3.19,0.55,11.4,7,4
28,9.6,0.680,0.24,2.2,0.087,5.0,28.0,0.99880,3.14,0.60,10.2,5,4
29,6.9,0.765,0.02,2.3,0.063,35.0,63.0,0.99750,3.57,0.78,9.9,5,2
30,8.9,0.120,0.45,1.8,0.075,10.0,21.0,0.99552,3.41,0.76,11.9,7,0
31,7.3,0.550,0.01,1.8,0.093,9.0,15.0,0.99514,3.35,0.58,11.0,7,1
32,9.5,0.885,0.27,2.3,0.084,31.0,145.0,0.99780,3.24,0.53,9.4,5,2
33,7.7,0.705,0.10,2.6,0.084,9.0,26.0,0.99760,3.39,0.49,9.7,5,4
34,10.9,0.530,0.49,4.6,0.118,10.0,17.0,1.00020,3.07,0.56,11.7,6,1
35,7.6,0.520,0.12,3.0,0.067,12.0,53.0,0.99710,3.36,0.57,9.1,5,4
36,9.8,0.440,0.47,2.5,0.063,9.0,28.0,0.99810,3.24,0.65,10.8,6,3
37,10.2,0.360,0.64,2.9,0.122,10.0,41.0,0.99800,3.23,0.66,12.5,6,0
38,9.4,0.340,0.37,2.2,0.075,5.0,13.0,0.99800,3.22,0.62,9.2,5,2
39,8.2,0.230,0.42,1.9,0.069,9.0,17.0,0.99376,3.21,0.54,12.3,6,0

## Stratified Kfold Cross Validation for Regression

In [66]:
import numpy as np
import pandas as pd

from sklearn import datasets
from sklearn import model_selection

In [67]:
X, y = datasets.make_regression(
    n_samples=15000, n_features=100, n_targets=1
)

In [68]:
print(X.shape)
print(y.shape)

(15000, 100)
(15000,)

In [69]:
df = pd.DataFrame(
    X,
    columns = [f"f_{i}" for i in range(X.shape[1])]
)

In [70]:
df['target'] = y
df.head().T

                 0           1         2          3           4
f_0       1.967542    0.672716 -1.432321  -1.387792   -0.336887
f_1       1.854855    0.632828 -0.072440   0.636867    3.313818
f_2       0.460540    0.509362 -1.044234   0.418167   -0.272132
f_3       0.326120    0.673803 -1.003566  -0.132490   -1.438493
f_4      -0.731037   -0.645938 -1.435351  -1.347781    0.350822
...            ...         ...       ...        ...         ...
f_96     -0.556217   -1.075441 -0.154406  -1.242681    0.129333
f_97     -0.175696    0.039597  0.433308   0.031565   -0.348519
f_98      1.113675   -0.266292  0.433224   0.764664   -1.322848
f_99     -2.161752   -0.251834 -0.934876   0.620653   -0.435942
target -117.950489 -258.574457 -2.201729 -39.959129  111.449937

[101 rows x 5 columns]

In [71]:
df['kfold'] = -1

df.sample(frac=1).reset_index(drop=True)

df.head()

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_92,f_93,f_94,f_95,f_96,f_97,f_98,f_99,target,kfold
0,1.967542,1.854855,0.460540,0.326120,-0.731037,-0.987923,-1.309334,-0.247570,-2.720942,-0.548896,...,0.991729,-0.340112,-1.652992,0.074148,-0.556217,-0.175696,1.113675,-2.161752,-117.950489,-1
1,0.672716,0.632828,0.509362,0.673803,-0.645938,-1.148611,-0.544225,-0.074524,0.564676,0.178681,...,-0.518833,-0.713084,0.989582,-0.617731,-1.075441,0.039597,-0.266292,-0.251834,-258.574457,-1
2,-1.432321,-0.072440,-1.044234,-1.003566,-1.435351,-0.861859,1.825421,1.129069,-0.128337,-0.743865,...,-1.099719,-0.143672,0.350580,1.710914,-0.154406,0.433308,0.433224,-0.934876,-2.201729,-1
3,-1.387792,0.636867,0.418167,-0.132490,-1.347781,0.215159,0.432248,-2.795407,0.107353,-1.043680,...,0.674103,-0.573381,-1.772891,-1.251047,-1.242681,0.031565,0.764664,0.620653,-39.959129,-1
4,-0.336887,3.313818,-0.272132,-1.438493,0.350822,1.293258,-0.241497,0.014920,-1.004706,0.257374,...,-0.738774,-0.458892,0.882883,0.770961,0.129333,-0.348519,-1.322848,-0.435942,111.449937,-1

In [72]:
num_bins = int(np.floor(1+np.log2(len(df))))
num_bins

14

In [73]:
df['bins'] = pd.cut(
    df['target'], bins=num_bins, labels=False
)
df.head(10)

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_93,f_94,f_95,f_96,f_97,f_98,f_99,target,kfold,bins
0,1.967542,1.854855,0.460540,0.326120,-0.731037,-0.987923,-1.309334,-0.247570,-2.720942,-0.548896,...,-0.340112,-1.652992,0.074148,-0.556217,-0.175696,1.113675,-2.161752,-117.950489,-1,5
1,0.672716,0.632828,0.509362,0.673803,-0.645938,-1.148611,-0.544225,-0.074524,0.564676,0.178681,...,-0.713084,0.989582,-0.617731,-1.075441,0.039597,-0.266292,-0.251834,-258.574457,-1,4
2,-1.432321,-0.072440,-1.044234,-1.003566,-1.435351,-0.861859,1.825421,1.129069,-0.128337,-0.743865,...,-0.143672,0.350580,1.710914,-0.154406,0.433308,0.433224,-0.934876,-2.201729,-1,6
3,-1.387792,0.636867,0.418167,-0.132490,-1.347781,0.215159,0.432248,-2.795407,0.107353,-1.043680,...,-0.573381,-1.772891,-1.251047,-1.242681,0.031565,0.764664,0.620653,-39.959129,-1,6
4,-0.336887,3.313818,-0.272132,-1.438493,0.350822,1.293258,-0.241497,0.014920,-1.004706,0.257374,...,-0.458892,0.882883,0.770961,0.129333,-0.348519,-1.322848,-0.435942,111.449937,-1,7
5,-0.856682,1.633816,-0.229653,-2.867030,-0.088404,-0.704221,-0.788929,-0.047854,-0.061309,1.999439,...,0.183731,-1.651159,1.028916,-1.426347,1.109946,-0.551905,0.095950,-38.022314,-1,6
6,-1.303923,0.267063,-0.183179,0.013900,1.441415,-1.688259,0.359311,0.095482,-0.689917,0.914621,...,0.612267,1.407159,0.446158,0.021823,-0.327045,-1.101037,-0.522676,86.544257,-1,7
7,-1.203279,0.010958,-0.325593,0.056834,-0.326211,-1.725494,-0.057669,2.067777,0.979042,0.657656,...,-0.714951,-0.855972,0.149836,0.716021,-0.204593,1.079766,0.242010,195.288591,-1,8
8,-1.035191,0.497880,0.354673,-1.394454,-2.309158,-0.261175,-2.659322,0.861639,0.205210,0.988709,...,-1.196474,0.979104,-0.642328,-0.768462,1.531743,-2.244935,2.681353,-116.929356,-1,5
9,-1.224117,1.123652,0.438441,0.661957,0.005516,-0.301802,-0.577667,1.038822,0.990871,0.457854,...,-0.378895,-0.002488,-0.868633,-0.045810,-1.092412,-0.895162,0.251747,-310.961145,-1,3

In [74]:
kf = model_selection.StratifiedKFold(n_splits=5)

In [75]:
for fold, (train, val) in enumerate(kf.split(X=df, y=df['bins'].to_numpy())):
    df.loc[val, 'kfold'] = fold

In [76]:
df = df.drop("bins", axis=1)

In [78]:
df = df.sample(frac=1).reset_index(drop=True)
df.head()

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_92,f_93,f_94,f_95,f_96,f_97,f_98,f_99,target,kfold
0,0.724803,0.040855,0.490291,-0.702374,1.033546,-0.782459,-0.579493,0.641723,0.606815,-2.847495,...,0.217763,0.261697,0.594830,-0.744485,1.637118,0.048521,1.026659,-0.635394,428.195188,4
1,0.855335,1.956527,0.447793,-0.593034,-0.913757,0.488722,1.328716,-0.766659,-0.621535,0.693623,...,0.203571,-0.370695,-0.697910,1.931609,-0.383146,-0.100557,-0.068662,-0.444882,-63.644546,4
2,-0.432510,-0.836206,-0.976407,1.505606,0.062862,-0.304209,0.096347,-0.229211,-0.068291,-0.564389,...,0.565413,0.907451,-1.043956,-0.281707,0.756896,0.751093,-1.077934,-0.173775,106.068784,2
3,1.933991,0.227200,-0.215649,0.185134,-0.050037,-1.296647,-0.045048,1.187739,1.322733,-0.073693,...,-0.310924,0.290656,0.787006,-0.526887,-0.087204,-0.914537,-0.292027,-0.894050,57.468536,4
4,-0.748884,1.040598,-0.089604,-0.286055,0.666842,0.391361,0.803722,-0.558950,0.641197,0.073365,...,-1.319432,-1.184415,0.113248,-1.485061,-0.118397,-0.048686,-1.571850,-0.017103,316.142138,2